// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Infrastructure.Context;

#nullable disable

namespace WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(TechChallenge1DbContext))]
    [Migration("20240414003426_AlterTableContactValueObj")]
    partial class AlterTableContactValueObj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("ContactId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Contact", b =>
                {
                    b.OwnsMany("WebApi.Domain.ValueObjects.EmailAddress", "EmailAddresses", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("ContactId", "Type", "Address");

                            b1.ToTable("ContactEmails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("WebApi.Domain.ValueObjects.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<string>("AreaCode")
                                .HasMaxLength(4)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("ContactId", "Type", "CountryCode", "AreaCode", "Number");

                            b1.ToTable("ContactPhoneNumbers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("EmailAddresses");

                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
